version: 2.1

jobs:
  test-pipes-pull:
    docker:
      - image: hseeberger/scala-sbt
    steps:
      - checkout
      - run: cd pipes-and-filters && sbt test

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-pipes-pull
